In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import codecs
%matplotlib inline

In [5]:
with codecs.open("carp_games.csv", "r", "Shift-JIS", "ignore") as file:
    games = pd.read_table(file, delimiter=",")

In [6]:
games["win"] = 1 if games["carp_score"]

           date  carp_score opponent_name  opponent_score
0    2016-04-01           4            巨人               6
1    2016-04-02           3            巨人               0
2    2016-04-03           3            巨人               4
3    2016-04-05          12          ヤクルト               5
4    2016-04-06           6          ヤクルト               3
5    2016-04-08           2            阪神               3
6    2016-04-09           6            阪神               2
7    2016-04-10           8            阪神               7
8    2016-04-12           3            中日               1
9    2016-04-14          10            中日               1
10   2016-04-16           5            巨人               6
11   2016-04-17           1            巨人               2
12   2016-04-19           6          DeNA               4
13   2016-04-20           0          DeNA              10
14   2016-04-22           9            阪神              12
15   2016-04-23           3            阪神               2
16   2016-04-24           2            阪神               6
17   2016-04-26          11          ヤクルト               3
18   2016-04-27           8          ヤクルト               0
19   2016-04-28           4          ヤクルト               6
20   2016-04-29           9            中日               4
21   2016-04-30          12            中日               2
22   2016-05-01          10            中日               7
23   2016-05-03           2            巨人               3
24   2016-05-04           6            巨人               1
25   2016-05-05           2            巨人               4
26   2016-05-06           0          DeNA               6
27   2016-05-07          10          DeNA               4
28   2016-05-08           1          DeNA               7
29   2016-05-10           6          ヤクルト               3
..          ...         ...           ...             ...
264  2017-08-27           5            中日               6
265  2017-08-29           2            巨人               1
266  2017-08-30           4            巨人               6
267  2017-08-31           1            巨人               3
268  2017-09-01           3          ヤクルト               2
269  2017-09-02           3          ヤクルト               1
270  2017-09-03           9          ヤクルト               2
271  2017-09-05           8            阪神               7
272  2017-09-06           4            阪神               3
273  2017-09-07           6            阪神               4
274  2017-09-08           3            中日               0
275  2017-09-09           9            中日               5
276  2017-09-10           4            中日               3
277  2017-09-12           1          DeNA               3
278  2017-09-13          12          DeNA               4
279  2017-09-14           5          DeNA               4
280  2017-09-16           4          ヤクルト               5
281  2017-09-18           3            阪神               2
282  2017-09-21           5            阪神               7
283  2017-09-22           5            巨人               0
284  2017-09-23           3            巨人               2
285  2017-09-24           2            中日               3
286  2017-09-28           3          ヤクルト               1
287  2017-09-30           5          DeNA               1
288  2017-10-01           7          DeNA              13
289  2017-10-18           3          DeNA               0
290  2017-10-19           2          DeNA               6
291  2017-10-20           0          DeNA               1
292  2017-10-23           3          DeNA               4
293  2017-10-24           3          DeNA               9

[294 rows x 4 columns]